package com.wei.lolbox.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.util.Log;

import org.greenrobot.greendao.AbstractDaoMaster;
import org.greenrobot.greendao.database.StandardDatabase;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseOpenHelper;
import org.greenrobot.greendao.identityscope.IdentityScopeType;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/**
 * Master of DAO (schema version 1): knows all DAOs.
 */
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(Database db, boolean ifNotExists) {
        HeroesDao.createTable(db, ifNotExists);
        HeroPositionDao.createTable(db, ifNotExists);
        HeroRolesDao.createTable(db, ifNotExists);
        PlayerCacheDao.createTable(db, ifNotExists);
        ServicerDao.createTable(db, ifNotExists);
        HomeTitleDao.createTable(db, ifNotExists);
        HomeVideoDao.createTable(db, ifNotExists);
        CharmingPhotoDao.createTable(db, ifNotExists);
        JiongPhotoDao.createTable(db, ifNotExists);
        MatchDao.createTable(db, ifNotExists);
        MsgTitleDao.createTable(db, ifNotExists);
        TopDao.createTable(db, ifNotExists);
        TopHeaderDao.createTable(db, ifNotExists);
        VideoesDao.createTable(db, ifNotExists);
        WallpaperDao.createTable(db, ifNotExists);
    }

    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(Database db, boolean ifExists) {
        HeroesDao.dropTable(db, ifExists);
        HeroPositionDao.dropTable(db, ifExists);
        HeroRolesDao.dropTable(db, ifExists);
        PlayerCacheDao.dropTable(db, ifExists);
        ServicerDao.dropTable(db, ifExists);
        HomeTitleDao.dropTable(db, ifExists);
        HomeVideoDao.dropTable(db, ifExists);
        CharmingPhotoDao.dropTable(db, ifExists);
        JiongPhotoDao.dropTable(db, ifExists);
        MatchDao.dropTable(db, ifExists);
        MsgTitleDao.dropTable(db, ifExists);
        TopDao.dropTable(db, ifExists);
        TopHeaderDao.dropTable(db, ifExists);
        VideoesDao.dropTable(db, ifExists);
        WallpaperDao.dropTable(db, ifExists);
    }

    /**
     * WARNING: Drops all table on Upgrade! Use only during development.
     * Convenience method using a {@link DevOpenHelper}.
     */
    public static DaoSession newDevSession(Context context, String name) {
        Database db = new DevOpenHelper(context, name).getWritableDb();
        DaoMaster daoMaster = new DaoMaster(db);
        return daoMaster.newSession();
    }

    public DaoMaster(SQLiteDatabase db) {
        this(new StandardDatabase(db));
    }

    public DaoMaster(Database db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(HeroesDao.class);
        registerDaoClass(HeroPositionDao.class);
        registerDaoClass(HeroRolesDao.class);
        registerDaoClass(PlayerCacheDao.class);
        registerDaoClass(ServicerDao.class);
        registerDaoClass(HomeTitleDao.class);
        registerDaoClass(HomeVideoDao.class);
        registerDaoClass(CharmingPhotoDao.class);
        registerDaoClass(JiongPhotoDao.class);
        registerDaoClass(MatchDao.class);
        registerDaoClass(MsgTitleDao.class);
        registerDaoClass(TopDao.class);
        registerDaoClass(TopHeaderDao.class);
        registerDaoClass(VideoesDao.class);
        registerDaoClass(WallpaperDao.class);
    }

    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }

    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }

    /**
     * Calls {@link #createAllTables(Database, boolean)} in {@link #onCreate(Database)} -
     */
    public static abstract class OpenHelper extends DatabaseOpenHelper {
        public OpenHelper(Context context, String name) {
            super(context, name, SCHEMA_VERSION);
        }

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(Database db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }

    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name) {
            super(context, name);
        }

        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(Database db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

}
